package br.usjt.green.journey.telas;

import br.usjt.green.journey.dao.PessoaDAO;
import br.usjt.green.journey.model.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author TheBerlatto
 */
public class LoginTela extends javax.swing.JFrame {

    /**
     * Creates new form LoginTela
     */
    public LoginTela() {
        super("Bem-vindo(a) a Green Journey!");
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sloganLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cadastroButton = new javax.swing.JButton();
        entrarButton = new javax.swing.JButton();
        sairButton = new javax.swing.JButton();
        senhaPasswordField = new javax.swing.JPasswordField();
        usernameTextField = new javax.swing.JTextField();
        logoLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fundoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(575, 375));
        setSize(new java.awt.Dimension(575, 375));
        getContentPane().setLayout(null);

        sloganLabel.setForeground(new java.awt.Color(51, 51, 51));
        sloganLabel.setText("Ajude o planeta com pequenas atitudes!");
        getContentPane().add(sloganLabel);
        sloganLabel.setBounds(30, 180, 240, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\ws-netbeans\\GreenJourney\\src\\main\\java\\br\\usjt\\green\\journey\\imagens\\teste-removebg-preview.png")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 110, 210, 70);

        cadastroButton.setText("Cadastre-se");
        cadastroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cadastroButton);
        cadastroButton.setBounds(335, 262, 120, 40);

        entrarButton.setText("Entrar");
        entrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(entrarButton);
        entrarButton.setBounds(409, 210, 90, 40);

        sairButton.setText("Sair");
        sairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairButtonActionPerformed(evt);
            }
        });
        getContentPane().add(sairButton);
        sairButton.setBounds(301, 210, 90, 40);

        senhaPasswordField.setBorder(javax.swing.BorderFactory.createTitledBorder("Senha:"));
        getContentPane().add(senhaPasswordField);
        senhaPasswordField.setBounds(301, 142, 200, 60);

        usernameTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Username:"));
        usernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(usernameTextField);
        usernameTextField.setBounds(301, 64, 200, 60);
        getContentPane().add(logoLabel);
        logoLabel.setBounds(50, 106, 0, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\ws-netbeans\\GreenJourney\\src\\main\\java\\br\\usjt\\green\\journey\\imagens\\foia canto superior esquerdo.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, 0, 80, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\ws-netbeans\\GreenJourney\\src\\main\\java\\br\\usjt\\green\\journey\\imagens\\foia canto superior direito.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(480, 0, 70, 60);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\ws-netbeans\\GreenJourney\\src\\main\\java\\br\\usjt\\green\\journey\\imagens\\foia_canto_inferior_esquerdo-removebg-preview.png")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-10, 280, 70, 60);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\ws-netbeans\\GreenJourney\\src\\main\\java\\br\\usjt\\green\\journey\\imagens\\foia canto inferior direito.png")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(480, 280, 80, 60);

        fundoLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\ws-netbeans\\GreenJourney\\src\\main\\java\\br\\usjt\\green\\journey\\imagens\\cor_de_fundo.jpg")); // NOI18N
        getContentPane().add(fundoLabel);
        fundoLabel.setBounds(0, 0, 560, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextFieldActionPerformed

    private void entrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarButtonActionPerformed
        //pegar o username que o usuário digitou
        String username = usernameTextField.getText();
        //pegar a senha na forma de um array de caracteres e depois converter para String
        String senha = new String(senhaPasswordField.getPassword());

            
        try {
            //verificar se o usuario existe no db
            Usuario usuario = new Usuario(username, senha);
            PessoaDAO dao = new PessoaDAO();
            if (dao.consultarSeExistir(usuario)) {
                //verifica se a conta digitada pertence ao admin
                if (username.equalsIgnoreCase("administrador") && senha.equals("adminadmin123")) {
                    JOptionPane.showMessageDialog(null, "Bem vindo(a), " + usuario.getUsername() + "!", "Olá!", JOptionPane.INFORMATION_MESSAGE);
                    Admin1 a1 = new Admin1();
                    a1.setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Bem vindo(a), " + usuario.getUsername() + "!", "Olá!", JOptionPane.INFORMATION_MESSAGE);
                    DashboardTela dt = new DashboardTela();
                    dt.receberUsername(username);
                    dt.setVisible(true);
                    this.dispose();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Usuário não cadastrado!", "Oops", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Problemas técnicos. Tente novamente mais tarde");
            e.printStackTrace();
        }
    }//GEN-LAST:event_entrarButtonActionPerformed

    private void cadastroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroButtonActionPerformed
        CadastroTela ct = new CadastroTela();
        ct.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cadastroButtonActionPerformed

    private void sairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_sairButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginTela().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastroButton;
    private javax.swing.JButton entrarButton;
    private javax.swing.JLabel fundoLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JButton sairButton;
    private javax.swing.JPasswordField senhaPasswordField;
    private javax.swing.JLabel sloganLabel;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
